### ISSUE TITLE
Selling a garage with drivers results in an error, and not being able to save my changes.

### ISSUE THREAD

**Issue by lemns** [LIPtoH/TS-SE-Tool#61]
```
TS SE Tool - 0.3.7.0
7/2/2022 2:08:29 PM
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

Stack Trace:
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at TS_SE_Tool.FormMain.PrepareGarages()
   at TS_SE_Tool.FormMain.buttonGaragesSell_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```
My road to the error goes as follows:

- Select a garage with vehicles and drivers inside;
![image](https://user-images.githubusercontent.com/31135486/176998284-cee74a6e-5748-4585-bf9a-b73578dcc051.png)
![image](https://user-images.githubusercontent.com/31135486/176998304-f017f32e-22fd-42f4-bde0-5dc5f4365fe9.png)
- Try to sell;
![image](https://user-images.githubusercontent.com/31135486/176998326-de56a0c0-bd68-466e-b146-e4e10e5f3d7f.png)
- Get the error.
![image](https://user-images.githubusercontent.com/31135486/176998336-ac98ef4f-118f-472b-9b6f-c6b416bb6b5f.png)

If needed, [here's](https://anonfiles.com/71ramdu2yc/42696C616C_7z) the save file.

Thanks :)

**Comment by LIPtoH** [comment]
Fixed
