### ISSUE TITLE
Decryption destroys saves | unable to edit

### ISSUE THREAD

**Issue by MyxRSC** [LIPtoH/TS-SE-Tool#67]
when I decrypt a save it doesn't let me edit anything and when I try to use that save it says that there is a problem with the save as shown in the attached photo. How can I fix this? It's happening with both ATS and ETS2
![save-load-problem](https://user-images.githubusercontent.com/113553708/190249213-33c8edc0-5523-46f8-96a8-835ed3644cc2.png)

**Comment by MyxRSC** [comment]
I currently have reverted to 0.3.0.0 as 0.3.7.0, 0.3.7.1, 0.3.7.2, 0.3.8.0 and 0.3.8.1 are all causing the problem in this post while 0.3.0.0 is not.

**Comment by Smatify** [comment]
```
TS SE Tool - 0.3.8.1
17.09.2022 09:30:39
Value was either too large or too small for an Int32.
player_job | cargo_model_index = 3130117026

TS SE Tool - 0.3.8.1
17.09.2022 09:30:56
Error during Writing save file
The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TS_SE_Tool.Save.Items.SiiNunit.PrintOut(UInt32 _version)
   at TS_SE_Tool.FormMain.NewWrireSaveFile(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```
