### ISSUE TITLE
Error during Writing save file

### ISSUE THREAD

**Issue by Ronn36** [LIPtoH/TS-SE-Tool#72]
How do i fix this ? 

 Error during Writing save file
Could not find file American Truck Simulator\profiles\547275636B6572526F6E\profile_backup.sii'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at TS_SE_Tool.FormMain.NewWrireSaveFile(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by Ronn36** [comment]
Anyone have or know how to fix ???
