### ISSUE TITLE
saves are not loaded. the cloud is disabled

### ISSUE THREAD

**Issue by Qva1t** [LIPtoH/TS-SE-Tool#97]
TS SE Tool - 0.3.9.1
27.07.2023 1:09:05
Входная строка имела неверный формат.
economy | achievements_added = nil

TS SE Tool - 0.3.9.1
27.07.2023 1:09:26
Error during Writing save file
The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TS_SE_Tool.Save.Items.SiiNunit.PrintOut(UInt32 _version)
   at TS_SE_Tool.FormMain.NewWrireSaveFile(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
![Screenshot_2](https://github.com/LIPtoH/TS-SE-Tool/assets/140210251/933dc793-6be9-4e76-9a67-139ad81e28cb)

![image](https://github.com/LIPtoH/TS-SE-Tool/assets/140210251/d302ee23-42ad-4ee2-b26d-9ea640ee024d)
![image](https://github.com/LIPtoH/TS-SE-Tool/assets/140210251/ab9fb679-0546-4f0a-a170-a20ae676ddf8)
![image](https://github.com/LIPtoH/TS-SE-Tool/assets/140210251/84150bb2-c97c-4721-bb00-3e2ad9cf24bf)

**Comment by Qva1t** [comment]
![Uploading изображение_2023-07-27_011353748.png…]()

**Comment by Qva1t** [comment]
![изображение_2023-07-27_011423324](https://github.com/LIPtoH/TS-SE-Tool/assets/140210251/ec93441b-479c-4e1e-9d63-9df4eb6553b2)
